### ISSUE TITLE
RequestData not in release

### ISSUE THREAD

**Issue by cnrudd** [ok2c/httpcomponents-jackson#12]
Hi,

I see a lot of references to this class https://github.com/ok2c/httpcomponents-jackson/blob/1ae2393df58cedbca3f560fd7c5688bf9f4e525d/hc5-async-json/src/test/java/com/ok2c/hc5/json/http/RequestData.java

in the examples, but this class is not in the release.

Is this an oversite, or is that class intended as an example of something we should make ourselves?

**Comment by ok2c** [comment]
@cnrudd `RequestData` class is not included in the official distribution. it is merely a test class that I personally cannot imagine being useful other than in a trivial demo.
