### ISSUE TITLE
Make Content-Type header control configurable

### ISSUE THREAD

**Issue by mattirn** [ok2c/httpcomponents-jackson#13]
@ok2c, thanks for the `hc5-async-json` lib! I'm in an unfortunate situation where servers I had to use erroneously set response header `Content-Type: text/html` even thought their response is perfect JSON. In `hc5-async-json` code there are controls for correct `Content-Type` header and thus I cannot use it as it is.
Do I have other options than clone the `httpcomponents-jackson` and modify the code? Would be great if `Content-Type` header control is made configurable (on/off).

**Comment by ok2c** [comment]
@mattirn I do not see a problem with making it configurable, however a better solution might be rewriting the response `Content-Type` header with a response interceptor.

**Comment by altaiezior** [comment]
@ok2c there is another use case here, so the library accepts an ObjectMapper which can be of different type so let's say it is a SmileMapper then since the check is on application/json we are not able to make it work.
