### ISSUE TITLE
Support long when parsing numbers

### ISSUE THREAD

**Issue by schulzp** [ok2c/httpcomponents-jackson#14]
When the `JsonTokenEventHandlerAdaptor` encounters a JSON `INT` token, it will parse it as `int` which breaks in case of large (negative) numbers, for example, 2153599188 (outside [-2147483648; 2147483647]). Since `DeserializationFeature`s don't have an effect in the current implementation, it is not possible work around this.

**Comment by schulzp** [comment]
Thank you! Would you have time to create a public release? Currently we run with a local build, but a public release would be highly appreciated. 🙏🏻

**Comment by ok2c** [comment]
> Thank you! Would you have time to create a public release? Currently we run with a local build, but a public release would be highly appreciated. 🙏🏻

@schulzp I will do my best to get around to cutting a new release sometime this or the next week.

**Comment by ok2c** [comment]
@schulzp `0.4.0` has been released.

**Comment by schulzp** [comment]
Thank you so much! Just in time for a new production release. 🚀
