### ISSUE TITLE
Requests with failure to connect result in NPE

### ISSUE THREAD

**Issue by scr-oath** [ok2c/httpcomponents-jackson#9]
Because HC5 notifies of failure without invoking the `AsyncResponseConsumer` `consumeResponse` method, the `entityConsumerRef` is not set in the `JsonStreamConsumer`.

That makes the falling call to get without checking for `null` throw a `NullPointerException`.
```json
    void failed(Exception cause) {
        entityConsumerRef.get().failed(cause);
    }
```

**Comment by ok2c** [comment]
Fixed by #10
